language: python

python:
    - "2.6"
    - "2.7"

before_install:
    - sudo apt-get -qq update
    - sudo apt-get -qq install libxml2-dev libxslt-dev ffmpeg python-dev sqlite
                               pep8
    - pip install nose-cov mock

install:
    - python setup.py develop
    - cp shiva/config/local.py.example shiva/config/local.py
    - echo "import os" >> shiva/config/local.py
    - echo "MEDIA_DIRS = (MediaDir(os.environ['HOME']),)" >> shiva/config/local.py

script:
    - find shiva -name '*.py' -exec pep8 '{}' \+
    - shiva-indexer
    - nosetests --with-cov --cov shiva
