language: python

python:
    - "2.6"
    - "2.7"

before_install:
    - sudo apt-get -qq update
    - sudo apt-get -qq install `cat dependencies.apt`
    - pip install -r dependencies-dev.pip
    - pip install --timeout 120 "python-dateutil==2.1"
    - if [ $(python -V 2>&1 | grep -c "2\.6\.") -eq 1 ]; then pip install unittest2; fi

install:
    - python setup.py develop
    - cp shiva/config/local.py.example shiva/config/local.py
    - echo "import os" >> shiva/config/local.py
    - echo "MEDIA_DIRS = (MediaDir(os.environ['HOME']),)" >> shiva/config/local.py

script:
    - find shiva -name '*.py' -exec pep8 --ignore=E128 '{}' \+
    - shiva-indexer
    - nosetests --with-cov --cov shiva

after_success:
    - coveralls
