"""empty message

Revision ID: 2d43584c9923
Revises: None
Create Date: 2012-03-31 14:41:07.675567

"""

# revision identifiers, used by Alembic.
revision = '2d43584c9923'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
