"""empty message

Revision ID: eeabb5b6b7a
Revises: 2d43584c9923
Create Date: 2012-03-31 14:41:26.966364

"""

# revision identifiers, used by Alembic.
revision = 'eeabb5b6b7a'
down_revision = '2d43584c9923'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hashes', u'pk')
    op.alter_column('hashes', 'digest', 
               existing_type=sa.VARCHAR(length=32), 
               nullable=False)
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hashes', sa.Column(u'pk', sa.INTEGER(), nullable=False))
    op.alter_column('hashes', 'digest', 
               existing_type=sa.VARCHAR(length=32), 
               nullable=True)
    ### end Alembic commands ###
